django_ipl/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('ipl', include('ipl.urls')),
    path('admin/', admin.site.urls),
]

ipl/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from . import views

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

app_name = 'ipl'

urlpatterns = [
    path('/',  views.IndexView.as_view(), name='index'),
    path('/assignment1', cache_page(CACHE_TTL)(views.AssignmentOneView.as_view()), name='assignment1'),
    path('/assignment2', cache_page(CACHE_TTL)(views.AssignmentTwoView.as_view()), name='assignment2'),
    path('/assignment3', cache_page(CACHE_TTL)(views.AssignmentThreeView.as_view()), name='assignment3'),
    path('/assignment4', cache_page(CACHE_TTL)(views.AssignmentFourView.as_view()), name='assignment4'),
    path('/assignment5', cache_page(CACHE_TTL)(views.AssignmentFiveView.as_view()), name='assignment5'),
    path('/assignment1/plot', cache_page(CACHE_TTL)(views.AssignmentOnePlotView.as_view()), name='assignment1plot'),
    path('/assignment2/plot', cache_page(CACHE_TTL)(views.assignment2plot), name='assignment2plot'),
    path('/assignment3/plot', cache_page(CACHE_TTL)(views.AssignmentThreePlotView.as_view()), name='assignment3plot'),
    path('/assignment4/plot', cache_page(CACHE_TTL)(views.AssignmentFourPlotView.as_view()), name='assignment4plot'),
    path('/assignment5/plot', cache_page(CACHE_TTL)(views.AssignmentFivePlotView.as_view()), name='assignment5plot'),

]

ipl/models.py
from django.db import models


class Matches(models.Model):

    season = models.IntegerField(default=0)
    city = models.CharField(max_length=100)
    date = models.DateField()
    team1 = models.CharField(max_length=200)
    team2 = models.CharField(max_length=200)
    toss_winner = models.CharField(max_length=200)
    toss_decision = models.CharField(max_length=100)
    result = models.CharField(max_length=100)
    dl_applied = models.BooleanField()
    winner = models.CharField(max_length=200)
    win_by_runs = models.IntegerField(default=0)
    win_by_wickets = models.IntegerField(default=0)
    player_of_match = models.CharField(max_length=100)
    venue = models.CharField(max_length=200)
    umpire1 = models.CharField(max_length=100)
    umpire2 = models.CharField(max_length=100)
    umpire3 = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.team1} vs {self.team2} season {self.season}"


class Deliveries(models.Model):

    match_id = models.IntegerField(default=0)
    inning = models.IntegerField(default=0)
    batting_team = models.CharField(max_length=200)
    bowling_team = models.CharField(max_length=200)
    over = models.IntegerField(default=0)
    ball = models.IntegerField(default=0)
    batsman = models.CharField(max_length=100)
    non_striker = models.CharField(max_length=100)
    bowler = models.CharField(max_length=100)
    is_super_over = models.IntegerField(default=0)
    wide_runs = models.IntegerField(default=0)
    bye_runs = models.IntegerField(default=0)
    legbye_runs = models.IntegerField(default=0)
    noball_runs = models.IntegerField(default=0)
    penalty_runs = models.IntegerField(default=0)
    batsman_runs = models.IntegerField(default=0)
    extra_runs = models.IntegerField(default=0)
    total_runs = models.IntegerField(default=0)
    player_dismissed = models.CharField(max_length=100)
    dismissal_kind = models.CharField(max_length=100)
    fielder = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.batting_team} vs {self.bowling_team} match# {self.match_id}"

ipl/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic
from ipl.models import Matches, Deliveries
from django.db.models import Count, Sum, Avg


class IndexView(generic.TemplateView):

    template_name = 'ipl/index.html'


class AssignmentOneView(generic.ListView):

    template_name = 'ipl/assignment1.html'
    context_object_name = 'season_list'

    
    def get_queryset(self):
        return Matches.objects.values('season').annotate(Count('season')).order_by()


class AssignmentTwoView(generic.ListView):

    template_name = 'ipl/assignment2.html'
    context_object_name = 'winner_season_list'

    
    def get_queryset(self):
        return Matches.objects.values('winner', 'season').annotate(Count('winner')).order_by()


class AssignmentThreeView(generic.ListView):

    template_name = 'ipl/assignment3.html'
    context_object_name = 'extra_runs_conceded'

    def get_queryset(self):
        return Deliveries.objects.values('bowling_team').annotate(Sum('extra_runs')).filter(match_id__in=Matches.objects.values('id').filter(season=2016))


class AssignmentFourView(generic.ListView):

    template_name = 'ipl/assignment4.html'
    context_object_name = 'economical_bowlers'

    
    def get_queryset(self):
        return Deliveries.objects.values('bowler').annotate(economy=Avg('total_runs') * 6).filter(match_id__in=Matches.objects.values('id').filter(season=2015)).order_by('economy')[:10]


class AssignmentFiveView(generic.ListView):

    template_name = 'ipl/assignment5.html'
    context_object_name = 'runrates'

    def runrate(self, team):
        s = 0
        for overs in team:
            s += overs['total_runs__sum']
            overs['total_runs__sum'] = s

        for overs in team:
            overs['total_runs__sum'] = overs['total_runs__sum'] / overs['over']

        return team

    
    def get_queryset(self):
        rr = Deliveries.objects.values('over').annotate(Sum('total_runs')).filter(
            match_id=513, batting_team='Rajasthan Royals')
        mi = Deliveries.objects.values('over').annotate(
            Sum('total_runs')).filter(match_id=513, batting_team='Mumbai Indians')

        return (self.runrate(rr), self.runrate(mi))


class AssignmentOnePlotView(generic.ListView):
    template_name = 'ipl/assignment1plot.html'
    context_object_name = 'season_list'

    
    def get_queryset(self):
        return AssignmentOneView().get_queryset()


def assignment2plot(request):
    winners = AssignmentTwoView().get_queryset()
    winners_per_season = {}
    for rows in winners:
        if rows['winner'] != '':
            if rows['winner'] not in winners_per_season.keys():
                winners_per_season[rows['winner']] = {rows['season']:rows['winner__count']}
            else:
                winners_per_season[rows['winner']][rows['season']] = rows['winner__count']

    season_list = [season for season in range(2008, 2018)]
    for team, wins in winners_per_season.items():
        for season in season_list:
            if season not in wins.keys():
                wins[season] = 0

        sorted_wins = sorted(wins)
        sorted_win_dict = {}
        for win in sorted_wins:
            sorted_win_dict[win] = wins[win]
        winners_per_season[team] = sorted_win_dict

    return render(request, 'ipl/assignment2plot.html', {'winners_per_season': winners_per_season})



class AssignmentThreePlotView(generic.ListView):
    template_name = 'ipl/assignment3plot.html'
    context_object_name = 'extra_runs_conceded'

    
    def get_queryset(self):
        return AssignmentThreeView().get_queryset()


class AssignmentFourPlotView(generic.ListView):
    template_name = 'ipl/assignment4plot.html'
    context_object_name = 'economical_bowlers'

    
    def get_queryset(self):
        return AssignmentFourView().get_queryset()


class AssignmentFivePlotView(generic.ListView):
    template_name = 'ipl/assignment5plot.html'
    context_object_name = 'runrates'

    
    def get_queryset(self):
        return AssignmentFiveView().get_queryset()

ipl/templates/ipl/assignment1.html
{% extends "ipl/basic.html" %}
{% load cache %}
{% block title %}Assignment One{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment One page.

{% if season_list %}
<ul>
    {% for season in season_list %}
    <li>{{season.season}} -- {{season.season__count}}</li>
    {% endfor %}
</ul>
{% else %}
<p>
    Something Went Wrong
</p>
{% endif %}

<a href="{% url 'ipl:index' %}">Back to Start</a> <a href="{% url 'ipl:assignment1plot' %}">Go to Chart</a>
{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment1plot.html
{% extends "ipl/basic.html" %}
{% load cache %}


{% block title %}Assignment One Plot{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment One plot.

<div id="container"></div>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Matches per Season'
        },
        xAxis: {
            categories: [
                {% for season in season_list %}
                    '{{ season.season }}'
                    {% if not forloop.last %}, {% endif %}
        {% endfor %}
            ]
        },
        series: [{
            name: 'Seasons',
            data: [
                {% for season in season_list %}
                    {{ season.season__count }}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
            ]
        }]
    });
</script>


{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment2.html
{% extends "ipl/basic.html" %}
{% load cache %}
{% block title %}Assignment Two{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment Two page.
{{winners_per_season}}
{% if winners_per_season %}
{% for winner in winners_per_season %}
<p>
    {{winner}}
</p>
{% endfor %}

{% endif %}

<a href="{% url 'ipl:index' %}">Back to Start</a> <a href="{% url 'ipl:assignment2plot' %}">Go to Chart</a>
{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment2plot.html
{% extends "ipl/basic.html" %}
{% load cache %}

{% block title %}Assignment Two Plot{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment Two plot.

<div id="container" style="height:600px"></div>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Stacked column chart'
        },
        xAxis: {
            categories: [{% for team_data in winners_per_season.values %}{% if forloop.first %}{% for season in team_data.keys %} {% if forloop.last %} {{ season }} {% else %} {{ season }}, {% endif %} {% endfor %} {% endif %} {% endfor %}]
        
    },
    yAxis: {
        min: 0,
            title: {
            text: 'Winners per Season'
        },
        stackLabels: {
            enabled: true,
                style: {
                fontWeight: 'bold',
                    color: (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
            }
        }
    },
    legend: {
        align: 'right',
            x: -30,
                verticalAlign: 'top',
                    y: 25,
                        floating: true,
                            backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
                                borderColor: '#CCC',
                                    borderWidth: 1,
                                        shadow: false
    },
    tooltip: {
        headerFormat: '<b>{point.x}</b><br/>',
            pointFormat: '{series.name}: {point.y}<br/>Total: {point.stackTotal}'
    },
    plotOptions: {
        column: {
            stacking: 'normal',
                dataLabels: {
                enabled: true,
                    color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
            }
        }
    },
    series: [{% for team, wins in winners_per_season.items %}
    {
        name: '{{ team }}',
            data: [{% for win in wins.values %} {{ win }} {% if not forloop.last %}, {% endif %} {% endfor %}]
        }{% if not forloop.last %}, {% endif %}
    {% endfor %}
    ] 
});
</script>

{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment3.html
{% extends "ipl/basic.html" %}
{% load cache %}
{% block title %}Assignment Three{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment Three page.

{% if extra_runs_conceded %}

{% for run in extra_runs_conceded %}
<p>{{ run.bowling_team }} -- {{ run.extra_runs__sum }} </p>
{% endfor %}

{% endif %}

<a href="{% url 'ipl:index' %}">Back to Start</a> <a href="{% url 'ipl:assignment3plot' %}">Go to Chart</a>
{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment3plot.html
{% extends "ipl/basic.html" %}
{% load cache %}
{% block title %}Assignment Three Plot{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment One plot.

<div id="container"></div>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Matches per Season'
        },
        xAxis: {
            categories: [
                {% for team in extra_runs_conceded %}
                    '{{ team.bowling_team }}'
                    {% if not forloop.last %}, {% endif %}
        {% endfor %}
            ]
        },
        series: [{
            name: 'Extra Runs',
            data: [
                {% for team in extra_runs_conceded %}
                    {{ team.extra_runs__sum }}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
            ]
        }]
    });
</script>
<a href="{% url 'ipl:assignment3' %}">Go back</a>

{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment4.html
{% extends "ipl/basic.html" %}
{% load cache %}

{% block title %}Assignment Four{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment Four page.


{% if economical_bowlers %}
{% for bowler in economical_bowlers %}
<p> {{ bowler.bowler }} -- {{ bowler.economy}} </p>
{% endfor %}

{% endif %}

<a href="{% url 'ipl:index' %}">Back to Start</a> <a href="{% url 'ipl:assignment4plot' %}">Go to Chart</a>
{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment4plot.html
{% extends "ipl/basic.html" %}
{% load cache %}
{% block title %}Assignment Four Plot{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment One plot.

<div id="container"></div>
<script>
    Highcharts.chart('container', {
        chart: {
            type: 'column'
        },
        title: {
            text: 'Economical Bowlers'
        },
        xAxis: {
            categories: [
                {% for bowler in economical_bowlers %}
                    '{{ bowler.bowler }}'
                    {% if not forloop.last %}, {% endif %}
        {% endfor %}
            ]
        },
        series: [{
            name: 'Economies',
            data: [
                {% for bowler in economical_bowlers %}
                {{ bowler.economy }}
        {% if not forloop.last %}, {% endif %}
    {% endfor %}
            ]
        }]
    });
</script>
<a href="{% url 'ipl:assignment4' %}">Go back</a>


{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment5.html
{% extends "ipl/basic.html" %}
{% load cache %}

{% block title %}Assignment Five{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment Five page.

{% if runrates %}
{% for runrate in runrates %}
{% for run in runrate %}
<p>{{run.over}} -- {{ run.total_runs__sum }}</p>
{% endfor %}
{% endfor %}
{% endif %}

<a href="{% url 'ipl:index' %}">Back to Start</a>

{% endblock %}
{% endcache %}

ipl/templates/ipl/assignment5plot.html
{% extends "ipl/basic.html" %}
{% load cache %}

{% block title %}Assignment Five plot{% endblock %}
{% cache 500 content %}
{% block content %}
This is my Assignment One plot.
<div id="container"></div>
<script>
    Highcharts.chart('container', {

        title: {
            text: 'Mumbai Indians vs Rajasthan Royals Match# 513'
        },


        yAxis: {
            title: {
                text: 'Runrates'
            }
        },
        xAxis: {
            title: {
                text: 'Overs'
            }
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle'
        },


        series: [{
            name: 'Rajasthan Royals',
            data: [{% for runrate in runrates %}
            {% if forloop.counter == 1 %}
            {% for run in runrate %}
    {{ run.total_runs__sum }}
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% endif %}
    {% endfor %}]

}, {
        name: 'Mumbai Indians',
            data: [{% for runrate in runrates %}
    {% if forloop.counter == 2 %}
    {% for run in runrate %}
    {{ run.total_runs__sum }}
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% endif %}
    {% endfor %}]
}],

    responsive: {
        rules: [{
            condition: {
                maxWidth: 500
            },
            chartOptions: {
                legend: {
                    layout: 'horizontal',
                    align: 'center',
                    verticalAlign: 'bottom'
                }
            }
        }]
    }

});
</script>


{% endblock %}
{% endcache %}

ipl/templates/ipl/basic.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>{% block title %}IPL{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://code.highcharts.com/highcharts.src.js"></script>
</head>

<body>
    {% block content %}{% endblock %}
</body>

</html>

ipl/templates/ipl/index.html
Click the assignment you want to see:

<ul>
    <li><a href="{% url 'ipl:assignment1' %}">Assignment One</a></li>
    <li><a href="{% url 'ipl:assignment2' %}">Assignment Two</a></li>
    <li><a href="{% url 'ipl:assignment3' %}">Assignment Three</a></li>
    <li><a href="{% url 'ipl:assignment4' %}">Assignment Four</a></li>
    <li><a href="{% url 'ipl:assignment5' %}">Assignment Five</a></li>
</ul>